POST http://localhost:3001/api/case/
Content-Type: application/json

{
   "customerName":"Mustermax",
   "startDate":"Wed Jan 04 2023 08:22:33 GMT+0100 (Central European Standard Time)",
   "isFinished":false,
}